apiVersion: v1
kind: Secret
metadata:
  name: capd-values
  namespace: default
stringData:
  data.yml: |
    cluster:
      name: kind-0
      masterNodes: 1
      workerNodes: 3
      version: v1.21.1
